//alert(1);

var arr=["A great attitude becomes a great day, which becomes a great month, which becomes a great year, which becomes a great life.",
"The only time you should look back, is to see how far you've come.",
"I am in charge of how I feel and today I am choosing happiness.",
"The only thing worse than being blind is have sight and no vision.",
"Good things come to those who wait work their asses off and never give up",
"If you're making mistakes it means you're out there doing something.",
"When you are happy, you enjoy the music. But, when you are sad, you understand the lyrics.",
"Once you replace negative thoughts with positive ones, you'll start having positive results.",
"Dream. Believe. Do. Repeat.",
"Today I will do what others won't, so tomorrow I can accomplish what others can't!",
"Be the type of person you want to meet",
"Instead of wondering when your next vacation is, maybe you should set up a life you don't need to escape from.",
"Don't carry your mistakes around with you. Instead, place them under your feet and use them as stepping stones!",
"The soul always knows what to do to heal itself. The challenge is to silence the mind.",
"Most of the things we worry about are things that won't even matter to us a few months from now.",
"I can't afford to hate anyone. I don't have that kind of time.",
"If you have the courage to begin, you have the courage to succeed.",
"Sometimes you have to stop staring at your problems and start seeing how beautiful your life really is.",
"You can't control where you come from, but you can always control where you are going.",
"Every day may not be good…but there is something good in every day.",
"Strong is what happens when you run out of weak.",
"Your desire to change must be greater than your desire to stay the same.",
"The only disability in life is a bad attitude.",
"The secret of change is to focus all of your energy, not on fighting the old, but on building the new.",
"Changing the world begins with the very personal process of changing yourself. The only place change can begin is where you are, and the only time you can begin is always now.",
"There’s a difference between interest and commitment. When you’re interested in doing something, you do it when it’s convenient. When you’re committed to something, you accept no excuses; only results.",
"We stopped checking for monsters under the bed when we realized they were inside of us.",
"The meaning of life is to find your gift. The purpose of life is to give it away.",
"If we wait until we’re ready, we’ll be waiting for the rest of our lives.",
"Sometimes the dreams that come true are the dreams you never even knew you had.",
"The moment you accept responsibility for everything in your life is the moment you gain the power to change anything in your life.",
"It is not the mountain we conquer, but ourselves.",
"People inspire you, or they drain you. Pick them wisely",
"Life is too short to live the same day twice.",
"Successful people have fear. Successful people have doubts. Successful people have worries. They just don't let these feelings stop them.",
"They may be smarter than you. They may have more money than you. They may come from a different city or a better family. But they can never outwork you. And they can never out prepare you. And they just can’t out practice you. And that’s why you’ll win!",
"Life is not something that ‘has’ meaning – it’s something we give meaning to. You don’t ‘end up’ with a meaningful life, you create it.",
"Dear Past, thank you for all the lessons. Dear Future, I’m now ready.",
"I always wonder why birds stay in the same place when they can fly anywhere on the earth. Then I ask myself the same question.",
"The one who follows the crowd will usually get no further than the crowd. The one who walks alone, is likely to find himself in places no one has ever been.",
"Apologizing does not always mean you are wrong, it just means that you value your relationship more than your ego.",
"Find something you are passionate about and keep tremendously interested in it.",
"No matter how hard the past, you can always begin again.",
"Become the leader of your life. Lead yourself to where you want to be. Breathe life back into your ambitions, your desires, your goals, your relationships.",
"Do something that your future self will thank you for.",
"Be who you are and say what you feel, because those who mind don’t matter and those who matter don’t mind.",
"What am I living for and what am I dying for are the same question.",
"There is only one happiness in this life, to love and be loved.",
"The greatest healing therapy is friendship and love.",
"No one ever finds life worth living – one has to make it worth living.",
"People who are crazy enough to think they can change the world, are the ones who do.",
"If you organize your life around your passion, you can turn your passion into your story and then turn your story into something bigger - something that matters.",
"Keep your dreams alive. Understand to achieve anything requires faith and belief in yourself, vision, hard work, determination, and dedication. Remember all things are possible for those who believe.",
"Success works as a cycle – growth and contraction, balancing and unbalancing – all while you’re encountering hurdles that get higher and higher over time.",
"Success is not final, failure is not fatal: it is the courage to continue that counts.",
" If you are always trying to be normal, you will never know how amazing you can be.",
"A Brother may not be a Friend, but a Friend will always be a Brother.",
"Without a plan you're going to stay where you are. It's time to make a move.",
"You can't put a limit on anything. The more you dream, the farther you get.",
"To be a champ you have to believe in yourself when nobody else will.",
"All our dreams can come true - if we have the courage to pursue them.","All things are difficult before they are easy."];

var randomNumber = Math.floor(Math.random()*arr.length);

document.write("<h1><i>"+arr[randomNumber]+"</i></h1>");

/*var a=document.getElementById("#new");
a.innerHTML+=arr[randomNumber];
alert(a.innerHTML);  
*/
